#ifndef stokes_include_file
#define stokes_include_file

#include "base_block_problem.h"

// Forward declare the tester class
template <typename Integral>
class StokesTester;

using namespace dealii;

/**
 * Solve the Poisson problem, with Dirichlet or Neumann boundary conditions, on
 * all geometries that can be generated by the functions in the GridGenerator
 * namespace.
 */
template <int dim>
class Stokes : public BaseBlockProblem<dim>
{
public:
  /**
   * Constructor. Initialize all parameters, including the base class, and make
   * sure the class is ready to run.
   */
  Stokes();

  /**
   * Destroy the Stokes object
   */
  ~Stokes() = default;

  using CopyData    = typename BaseBlockProblem<dim>::CopyData;
  using ScratchData = typename BaseBlockProblem<dim>::ScratchData;

protected:
  /**
   * Explicitly assemble the Stokes problem.
   */
  virtual void
  assemble_system_one_cell(
    const typename DoFHandler<dim>::active_cell_iterator &cell,
    ScratchData &                                         scratch,
    CopyData &                                            copy) override;

  virtual void
  solve() override;

  virtual void
  estimate() override;

//  /**
//   * Extractor to use in the assembly routine.
//   */
//  FEValuesExtractors::Vector velocity;
//
//  /**
//   * Extractor to use in the assembly routine.
//   */
//  FEValuesExtractors::Scalar pressure;

  template <typename Integral>
  friend class StokesTester;
};

#endif
